print("Please enter the Total Games played in Tournament")
TP=int(input())
print("Total games played",TP)
print("Please enter the Total Games won in Tournament")
won=int(input())
print("Total games played",won)
print("Please enter the Total Games lost in Tournament")
lost=int(input())
print("Total games played",lost)
print("Please enter the Total Games tied in Tournament")
tied=int(input())
print("Total games played",tied)